// Galactic Database image-management revision
(() => {
'use strict';
const cfg=window.DESTINY_GM_CONFIG;if(!cfg?.url||!cfg?.key){document.body.innerHTML='<main><section class="card error">GM portal configuration is unavailable.</section></main>';return;}
const db=window.supabase.createClient(cfg.url,cfg.key),tables=['npcs','locations','factions','missions','sessions','discoveries'],longFields=new Set(['description','relationship','player_notes','briefing','objectives','discoveries','outcome','rewards','summary','key_events','loot','consequences','significance','capabilities','clues','crew_history','goals','resources']),readonlyFields=new Set(['created_at','updated_at']),bucket='galactic-database-images';let currentTable='npcs',rows=[],current=null,pendingImage=null,removeImage=false,previewUrl=null;const $=id=>document.getElementById(id),escapeHtml=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),displayName=r=>r.name||r.title||(r.number!=null?`Session ${r.number}`:r.id)||'Untitled',status=(id,text,error=false)=>{const el=$(id);el.textContent=text;el.className=error?'error':'ok';},publicImage=path=>path?db.storage.from(bucket).getPublicUrl(path).data.publicUrl:'';
async function authorize(){const{data:{user}}=await db.auth.getUser();if(!user){$('login').classList.remove('hidden');$('app').classList.add('hidden');return;}const{data,error}=await db.rpc('is_gm');if(error||data!==true){await db.auth.signOut();$('login').classList.remove('hidden');$('app').classList.add('hidden');status('loginMessage','This account is not authorized as the Destiny GM.',true);return;}$('login').classList.add('hidden');$('app').classList.remove('hidden');$('identity').textContent=`AUTHORIZED GM // ${user.email||user.id}`;buildTabs();await loadRows();}
function buildTabs(){const nav=$('tabs');nav.innerHTML='';for(const t of tables){const b=document.createElement('button');b.textContent=t.toUpperCase();b.className=t===currentTable?'active':'';b.onclick=async()=>{currentTable=t;current=null;$('editor').classList.add('hidden');buildTabs();await loadRows();};nav.appendChild(b);}}
async function loadRows(){$('records').innerHTML='<div>SCANNING DATABASE…</div>';const{data,error}=await db.from(currentTable).select('*');if(error){$('records').innerHTML=`<div class="error">${escapeHtml(error.message)}</div>`;return;}rows=data||[];renderRows();}
function renderRows(){const q=$('search').value.trim().toLowerCase(),host=$('records');host.innerHTML='';const filtered=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q));for(const r of filtered){const d=document.createElement('div');d.className='record';d.innerHTML=`<strong>${escapeHtml(displayName(r))}</strong><small>${escapeHtml(r.status||r.type||r.planet||r.category||r.description||r.summary||'DATABASE RECORD')}</small>`;d.onclick=()=>openEditor(r);host.appendChild(d);}if(!filtered.length)host.innerHTML='<div>NO MATCHING RECORDS.</div>';}
function inferTemplate(){if(rows[0]){const o={};for(const k of Object.keys(rows[0]))if(!readonlyFields.has(k))o[k]=k==='id'?'':(typeof rows[0][k]==='number'?null:'');return o;}return{id:'',name:'',image_path:''};}
function validateImage(file){const allowed=['image/jpeg','image/png','image/webp','image/gif'];if(!allowed.includes(file.type)){status('editorMessage','IMAGE REJECTED // USE JPG, PNG, WEBP, OR GIF.',true);return false;}if(file.size>10*1024*1024){status('editorMessage','IMAGE REJECTED // MAXIMUM FILE SIZE IS 10 MB.',true);return false;}return true;}
function queueImage(file,wrap){if(!file||!validateImage(file))return;pendingImage=file;removeImage=false;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(file);let img=wrap.querySelector('.image-preview');if(!img){img=document.createElement('img');img.className='image-preview';wrap.insertBefore(img,wrap.querySelector('.image-dropzone'));}img.src=previewUrl;let name=wrap.querySelector('.image-file-name');if(!name){name=document.createElement('div');name.className='image-file-name';wrap.querySelector('.image-dropzone').after(name);}name.textContent=`QUEUED // ${file.name}`;status('editorMessage','IMAGE QUEUED // SAVE RECORD TO UPLOAD');}
function addImageManager(obj){const wrap=document.createElement('div');wrap.className='image-manager';const label=document.createElement('label');label.className='system-tag';label.textContent='VISUAL ARCHIVE // OPTIONAL IMAGE';wrap.appendChild(label);if(obj.image_path){const img=document.createElement('img');img.className='image-preview';img.src=publicImage(obj.image_path);img.alt=displayName(obj);wrap.appendChild(img);}const zone=document.createElement('div');zone.className='image-dropzone';zone.tabIndex=0;zone.innerHTML='<strong>ADD IMAGE</strong><span>DRAG AN IMAGE HERE<br>OR CLICK TO BROWSE</span>';const picker=document.createElement('input');picker.type='file';picker.accept='image/jpeg,image/png,image/webp,image/gif';zone.appendChild(picker);zone.onclick=()=>picker.click();zone.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();picker.click();}};picker.onclick=e=>e.stopPropagation();picker.onchange=()=>queueImage(picker.files?.[0],wrap);for(const evt of['dragenter','dragover'])zone.addEventListener(evt,e=>{e.preventDefault();e.stopPropagation();zone.classList.add('dragover');});for(const evt of['dragleave','drop'])zone.addEventListener(evt,e=>{e.preventDefault();e.stopPropagation();zone.classList.remove('dragover');});zone.addEventListener('drop',e=>queueImage(e.dataTransfer?.files?.[0],wrap));wrap.appendChild(zone);if(obj.image_path){const actions=document.createElement('div');actions.className='image-actions';const clear=document.createElement('button');clear.type='button';clear.className='danger';clear.textContent='REMOVE IMAGE';clear.onclick=()=>{pendingImage=null;removeImage=true;if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null;}wrap.querySelector('.image-preview')?.remove();wrap.querySelector('.image-file-name')?.remove();status('editorMessage','IMAGE MARKED FOR REMOVAL // SAVE TO CONFIRM');};actions.appendChild(clear);wrap.appendChild(actions);}$('fields').appendChild(wrap);}
function openEditor(record=null){current=record;pendingImage=null;removeImage=false;if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null;}$('editorTitle').textContent=(record?'EDIT // ':'NEW // ')+currentTable.toUpperCase();$('fields').innerHTML='';const obj=record?structuredClone(record):inferTemplate();addImageManager(obj);for(const[key,value]of Object.entries(obj)){if(readonlyFields.has(key)||key==='image_path')continue;const wrap=document.createElement('div');wrap.className='field'+(longFields.has(key)?' long':'');const label=document.createElement('label');label.textContent=key.replaceAll('_',' ');wrap.appendChild(label);const input=longFields.has(key)?document.createElement('textarea'):document.createElement('input');input.dataset.key=key;if(typeof value==='object'&&value!==null)input.value=JSON.stringify(value);else input.value=value??'';wrap.appendChild(input);$('fields').appendChild(wrap);}$('deleteButton').classList.toggle('hidden',!record);$('editorMessage').textContent='';$('editor').classList.remove('hidden');$('editor').scrollIntoView({behavior:'smooth'});}
function collect(){const obj={};for(const input of $('fields').querySelectorAll('[data-key]')){let v=input.value,key=input.dataset.key;if(v.trim().startsWith('[')||v.trim().startsWith('{')){try{v=JSON.parse(v)}catch{}}obj[key]=v;}return obj;}
async function uploadImage(id){const extByType={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif'},ext=extByType[pendingImage.type]||'jpg',safeId=String(id).replace(/[^a-zA-Z0-9_-]/g,'-'),path=`${currentTable}/${safeId}-${Date.now()}.${ext}`;const{error}=await db.storage.from(bucket).upload(path,pendingImage,{contentType:pendingImage.type,upsert:false});if(error)throw error;return path;}
async function deleteImage(path){if(!path)return;const{error}=await db.storage.from(bucket).remove([path]);if(error)throw error;}
async function save(){let uploaded=null;try{const obj=collect(),id=current?.id||obj.id||`gm-${currentTable}-${Date.now()}`,oldPath=current?.image_path||null;if(!current)obj.id=id;let imagePath=oldPath;if(pendingImage){uploaded=await uploadImage(id);imagePath=uploaded;}else if(removeImage)imagePath=null;obj.image_path=imagePath;let result;if(current){delete obj.id;result=await db.from(currentTable).update(obj).eq('id',current.id).select();}else result=await db.from(currentTable).insert(obj).select();if(result.error)throw result.error;if(oldPath&&oldPath!==imagePath){try{await deleteImage(oldPath);}catch(e){console.warn('Old image cleanup failed',e);}}status('editorMessage','RECORD SYNCHRONIZED TO LIVE CHRONICLE.');await loadRows();if(result.data?.[0])openEditor(result.data[0]);}catch(error){if(uploaded){try{await deleteImage(uploaded);}catch(e){console.warn('Upload rollback failed',e);}}status('editorMessage',error.message||String(error),true);}}
async function remove(){if(!current?.id)return;if(!confirm(`Delete ${displayName(current)} from the live Chronicle database?`))return;const old=current.image_path;const{error}=await db.from(currentTable).delete().eq('id',current.id);if(error){status('editorMessage',error.message,true);return;}if(old){try{await deleteImage(old);}catch(e){console.warn('Image cleanup failed',e);}}current=null;$('editor').classList.add('hidden');await loadRows();}
$('loginButton').onclick=async()=>{const email=$('email').value.trim();if(!email){status('loginMessage','Enter your authorized email.',true);return;}const{error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:location.href.split('#')[0],shouldCreateUser:false}});status('loginMessage',error?error.message:'SECURE LOGIN LINK TRANSMITTED.',!!error);};$('logoutButton').onclick=async()=>{await db.auth.signOut();location.reload();};$('reloadButton').onclick=loadRows;$('search').oninput=renderRows;$('newButton').onclick=()=>openEditor();$('cancelButton').onclick=()=>$('editor').classList.add('hidden');$('saveButton').onclick=save;$('deleteButton').onclick=remove;db.auth.onAuthStateChange(()=>setTimeout(authorize,0));authorize();
})();
